### ISSUE TITLE
Project이름의 naming convention

### ISSUE THREAD

**Issue by benelog** [naver/egjs#1]
https://github.com/naver/ 의 기존의 프로젝트들은 소문자로 시작하고 단어사이의 구분은 "-"로 하고 있습니다. 

가급적 일관성을 위해서 유사한 형태를 권장합니다. EvergreenJS 가 따르는 다른 관례가 있으시다면 지금의 이름을  유지하셔도 괜찮습니다.

**Comment by sculove** [comment]
네 알겠습니다.
