### ISSUE TITLE
add github button to gh-pages

### ISSUE THREAD

**Issue by kishu** [naver/egjs#103]
https://ghbtns.com/

**Comment by kishu** [comment]
How about position of GitHub buttons???

![image](https://cloud.githubusercontent.com/assets/13197080/13038508/173e6e9a-d3d7-11e5-9228-b802bb9b4f45.png)

**Comment by sculove** [comment]
I love it!

**Comment by mixed** [comment]
LGTM!

**Comment by kishu** [comment]
check out http://naver.github.io/egjs/
