### ISSUE TITLE
When isn't circular, retrun wrong panel index number

### ISSUE THREAD

**Issue by netil** [naver/egjs#116]
Given options as below, previous index number should return as expected.

```js
    var f = new eg.Flicking("#mflick", {
        defaultIndex: 1,
        circular : false
    });

    f.getPrevIndex();  // return null instead of 0
```

**Comment by kishu** [comment]
```javascript
var f = new eg.Flicking("#mflick", {
  defaultIndex: 0,
  circular : false
});

f.getPrevIndex(); //null
```

The API document states ```getPrevIndex()``` returns type of number.
http://naver.github.io/egjs/latest/doc/eg.Flicking.html#getPrevIndex

However, when ```defaultIndex``` was given 0 it returns ```null```
