### ISSUE TITLE
eg.infiniteGrid unit test is broken on IE8

### ISSUE THREAD

**Issue by happyhj** [naver/egjs#121]
395 passed 16 failed
```
Error: "infiniteGrid initailization/destroy Test: check a append after a initialization (there aren't children)" failed, 'self.core.element' is null or not an object
Error: "infiniteGrid initailization/destroy Test: release event handler after destroy" failed, 'self.core.element' is null or not an object
```
<img width="1064" alt="screen shot 2016-02-12 at 7 36 00 pm" src="https://cloud.githubusercontent.com/assets/3903575/13004629/e924d92c-d1bf-11e5-8439-df6f7ade8a47.png">

**Comment by sculove** [comment]
![2016-04-26 9 05 49](https://cloud.githubusercontent.com/assets/1383952/14817506/b3138b90-0bf2-11e6-932a-1654a56c4a02.png)

this issue is no problem.
@happyhj Could you check it again?
Note that you should don't touch scroll because infiniteGrid controls scroll position.

**Comment by sculove** [comment]
IE8 fires double resize event. so I fix it.
![2016-04-27 2 28 27](https://cloud.githubusercontent.com/assets/1383952/14842658/7932bdb4-0c84-11e6-98be-cc79e102327d.png)
