### ISSUE TITLE
Change travis account

### ISSUE THREAD

**Issue by mixed** [naver/egjs#132]
Current trivis account is @sculove . We have to change @egjs account.

**Comment by mixed** [comment]
ref #113

**Comment by mixed** [comment]
and Codeclimate

**Comment by happyhj** [comment]
Travis-CI auth is directly linked with github auth. So there is no account to change for Travis-CI.
Code climate is same as Travis-CI. There is no account to change. 
We can use our own github account for managing Travis-CI and Code climate.

Sent request to Browserstack with shared email address.
