### ISSUE TITLE
Process can be stuck on very short interval touch

### ISSUE THREAD

**Issue by netil** [naver/egjs#153]
## Description
On `movableCoord` handle `touchEnd` event via Hammer.js's `.on("panend tap", this._panend);`.
Every user's touchEnd `_panend` is called, and inside of it, triggers `animationStart -> animationEnd` accordingly.
 
```js
// panend event handler
_panend: function(e) {
     var pos = this._pos;

     if (!this._isInterrupting() || !this._status.moveDistance) {
         return;
     }

     // Abort the animating post process when "tap" occurs

     if (e.type === "tap") {
	...
     } else {
         this._animateBy(
             this._getNextOffsetPos([
                 vX * (e.deltaX < 0 ? -1 : 1) * scale[0],
                 vY * (e.deltaY < 0 ? -1 : 1) * scale[1]
             ]),
             this._animationEnd, false, null, e);
     }

     this._status.moveDistance = null;
},
```
The problem occurs when user touch repeatedly and fastly in very short time.

## Steps to check or reproduce
1) via user's touch, `_panend()` is called
2) it triggers `animationStart` event
3) another `_panend()` call occurs before `animationEnd` was triggered
4) as result of `_panend` which assigns `this._status.moveDistance = null` at the end, the flow of the process can be stuck, due to ` !this._status.moveDistance` return condition

**Comment by sculove** [comment]
this issue is related to #23

**Comment by sculove** [comment]
if #23 is fixed, this issue also fixed. after merged, check it!
