### ISSUE TITLE
Write benchmark document for infiniteGrid

### ISSUE THREAD

**Issue by sculove** [naver/egjs#164]
## Description
- write benchmark document

**Comment by happyhj** [comment]
ref. #20

**Comment by sculove** [comment]
### check list
- initialization performance test
- append performance test
- memory profile
   - after initiailzation
   - after appending

**Comment by sculove** [comment]
### Compare eg.InfiniteGrid with Masorny
|구분|eg.InfiniteGrid|Masorny|
|----|----|----|
|dependency|jQuery 1.7.1+|[outlayer](https://github.com/metafizzy/outlayer), [get-size](https://github.com/desandro/get-size)
|file size| InfiniteGrid.min.js : 9,226 bytes| Masorny.min.js : 2,615 bytes|
|file size<br>(pkgd)| InfiniteGrid.pkgd.min.js : 21,181 bytes<br>(except jQuery)| Masorny.pkgd.min.js : 23,547 bytes|
|Browser support<br>(Desktop)|IE8+ and latest of modern browsers|IE10+ and latest of modern browsers|
|Browser support<br>(Mobile)|iOS7+, Android2.3+(except 3.0)|iOS, Android|
|Lisence|MIT|MIT|

**Comment by sculove** [comment]
### Initialization performance Test
- 1,000 cards that include image and texts.

|num|eg.InfiniteGrid|Masorny|
|----|--------------|---------|
|1| 962.04 ||
|2| 2076.37 ||
|3| 1076.26 ||
|4| 1342.82 ||
|5| 1083.09 ||
|6| 1104.80 ||
|7| 1072.29 ||
|8| 927.10 ||
|9| 923.08 ||
|10| 1016.29 ||
|**AVG**|  ||
> Time unit in milliseconds

**Comment by sculove** [comment]
### append performance test
https://www.youtube.com/watch?v=NyFtShC2yq8&feature=youtu.be

**Comment by sculove** [comment]
### memory profile (after appending)
- https://github.com/naver/egjs/issues/334

**Comment by sculove** [comment]
benchmark test is complete.
and we need to write an article.

**Comment by sculove** [comment]
### append perforamce test (Mobile)
- items (3,000 items appened)
