### ISSUE TITLE
scrollEnd doesn't pass left/top parameters

### ISSUE THREAD

**Issue by sculove** [naver/egjs#174]
## Description
scrollEnd event interface is weird.
also, document also is wrong.
http://naver.github.io/egjs/latest/doc/jQuery.html#event:scrollEnd

### AS-IS
```js
$(window).on("scrollend",function(e, p){
     p.top;
     p.left;
});
```

### TO-BE
```js
$(window).on("scrollend",function(e){
     e.top;
     e.left;
});
```

**Comment by sculove** [comment]
### jQueryUI Style : AS-IS style
> (jQuery Event,  options)
http://api.jqueryui.com/draggable/#event-create

### Jindo : TO-BE style
> (CustomEvent)
http://jindo.dev.naver.com/docs/jindo-component/1.14.0/doc/external/classes/jindo.DatePicker.html#event_afterDraw

### jQuery plugin, Slick, ..
http://learn.jquery.com/events/introduction-to-custom-events/
http://benalman.com/news/2010/03/jquery-special-events/
> (jQuery Event, arg1, arg2, ...)
```js
$( document ).on( "myCustomEvent", {
    foo: "bar"
}, function( event, arg1, arg2 ) {
    console.log( event.data.foo ); // "bar"
    console.log( arg1 );           // "bim"
    console.log( arg2 );           // "baz"
});
 
$( document ).trigger( "myCustomEvent", [ "bim", "baz" ] );
```
```js
$('.your-element').on('swipe', function(event, slick, direction){
  console.log(direction);
  // left
});
```

**Comment by mixed** [comment]
jQueryUI Style

**Comment by mixed** [comment]
Though Persist event is Jindo style It didn`t change style. Because depricated spec.
