### ISSUE TITLE
Rotate event is not fired In certain cases. (eg.isPortrait() issue)

### ISSUE THREAD

**Issue by woosh80** [naver/egjs#182]
## Description
egjs 1.1.0
rotate event is not fired In certain cases

When attach ‘resize' events which check the 'eg.isPortrait()' 
rotate event is not fired.

On first resize event, isPortrait(=isVertical) method update values of beforeVertical, beforeScreenWidth, beforeScreenHeight.
Then on fired rotate event, isVertical method compare with these already changed values, so the result of (beforeVertical !== currentVertical) on triggerRotate method is always false and it’s why rotate event not fire.

It seems that isPortrait method have to get the result without reset before values.
Check this issue plz.

## Steps to check or reproduce
`
$el.on(‘resize’, function() {
    if (eg.isPortrait()) {
        do something…
    }
});
`

`
$el.on(‘rotate’, function() {
    console.log(‘rotate event fired.’);
});
`

![image](https://cloud.githubusercontent.com/assets/3024542/14521945/2c587406-0267-11e6-9c4d-8d508c4fac93.png)
![image](https://cloud.githubusercontent.com/assets/3024542/14521954/348a0df6-0267-11e6-89c2-9882e511a64a.png)
![image](https://cloud.githubusercontent.com/assets/3024542/14521964/40d9155c-0267-11e6-8498-52c7e59a8309.png)

**Comment by jongmoon** [comment]
@mixed 

I have a question on rotate test case. `isVertical : If event is resize then second times call. and stay.`

Can you tell me the reason why `isVertical` must returns ```null``` (last lines) on below case?
Is it right for `isVertical` to have have ```true```? 

```js
var fakeDocument = {
  "documentElement" : {
  "clientWidth" : 100,
  "clientHeight" : 200
  }
};
 
var method = eg.invoke("rotate",[jQuery, null, fakeWindow, fakeDocument]);
method.isVertical();

// When
fakeDocument.documentElement.clientWidth =  100;
fakeDocument.documentElement.clientHeight =  200;
var isVertical = method.isVertical();

// Then
equal(isVertical,null);
```
