### ISSUE TITLE
How about changing file name of animate.js

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs#183]
## Description
There's jQuery plugin which enables transform on jQuery.animate() .

Despite its expansion for transform, its file name is `animate.js` for reason that it expands the ability of animate( ).

But I think nobody can assume its functionality. I think the file name must have the name which focuses its functionality not the name of its expansion target(here... animate)  

So I propose `transform.js`, How about it?

**Comment by mixed** [comment]
I agree with you. And `css.js` have to change file name too.(like `cssPrefix.js`...)

**Comment by sculove** [comment]
👍
