### ISSUE TITLE
Benchmark infiniteGrid

### ISSUE THREAD

**Issue by sculove** [naver/egjs#20]
research infiniteGrid VS masonry, infinity.js

**Comment by happyhj** [comment]
* [bench demo with eg.infiniteGrid](http://codepen.io/egjs/pen/MyJbLp)
* [bench demo with masonry](http://codepen.io/egjs/pen/ONWbGJ)

* Movie: [eg.infiniteGrid benchmark: append item performance](https://youtu.be/NyFtShC2yq8)
* Movie: [eg.infiniteGrid benchmark: layout performance](https://youtu.be/rpL7b6_XTVM)
