### ISSUE TITLE
persist - Fix unit test on Edge Browser

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs#210]
## Description
The below unit test cases failed.

![image](https://cloud.githubusercontent.com/assets/3255471/15207345/76683e78-1860-11e6-8e75-445b6d4b4a27.png)

## Steps to check or reproduce
Run ./test/unit/persist.test.html

**Comment by happyhj** [comment]
It was local file on EDGE issue.
http://stackoverflow.com/questions/32374875/localstorage-not-working-in-edge

Unit tests don't break on the edge browser.
