### ISSUE TITLE
add getPrevElement in eg.Flicking document

### ISSUE THREAD

**Issue by sculove** [naver/egjs#217]
## Description
![2016-05-18 3 05 00](https://cloud.githubusercontent.com/assets/1383952/15348978/ecc44fd2-1d09-11e6-803c-27de106cea01.png)

**Comment by sculove** [comment]
the pos.1 property of  `hold` event is omitted
https://github.com/naver/egjs/blob/master/src/flicking.js#L580-L581

**Comment by netil** [comment]
1) getPrevElement method jsdoc tag has been already added.
https://github.com/naver/egjs/blob/master/src/flicking.js#L1168

2) pos.1 will be added via new PR.
https://github.com/naver/egjs/blob/master/src/flicking.js#L659
