### ISSUE TITLE
Does flicking work well on old versions of IE?

### ISSUE THREAD

**Issue by incleaf** [naver/egjs#241]
I tested on old versions of IE, and seems flicking doesn't work on IE7 and IE8. is it right?

**Comment by jongmoon** [comment]
Thank you for your concern~ :)

Unfortunately flicking is working from IE10+ 

![image](https://cloud.githubusercontent.com/assets/3255471/15699474/1ad53ff4-2808-11e6-9325-da8e96e83e07.png)

http://naver.github.io/egjs/latest/doc/eg.Flicking.html

**Comment by incleaf** [comment]
Okay! Thanks :)

**Comment by netil** [comment]
@incleaf, even we documented to use over ie10, is able to use setting some option.

if you need to use on ie8, need to include [hammerjs.compatible](https://github.com/naver/hammerjs-compatible) as below.
```html
<!--[if IE 8]>
<script type="text/javascript" src="../dist/hammerjs.compatible.js"></script> 
<![endif]-->
```

And set inputType option to handle only mouse input
```js
new eg.Flicking("#id", {
	inputType: ["mouse"]
});
```

On ie9 it mostly works without inconvenience. Checkout the demo.
http://naver.github.io/egjs/demo/flicking/
