### ISSUE TITLE
Support pause/resume on transform

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs#242]
## Description

Now the pause/resume is not working on transform. But for more various animation effect, transform support is needed.
## Steps to check or reproduce

``` javascript
$el.animate({"transform": "rotate(20deg)"}, 4000);

//before 4000 ms, you can pause or resume
$el.pause(); 
```

**Comment by sculove** [comment]
Issue moved to [naver/egjs-pauseresume #5](https://github.com/naver/egjs-pauseresume/issues/5) via [**ZenHub**](https://www.zenhub.com/)
