### ISSUE TITLE
persist demo is written in korean

### ISSUE THREAD

**Issue by sculove** [naver/egjs#250]
## Description
persist demo is written in korea.
correct comment and text.

**Comment by sculove** [comment]
this demo uses deprecated api. 
and there is no necessity for chrome browser to save scroll position.

**Comment by happyhj** [comment]
This is the demo written in korean.
https://github.com/naver/egjs/blob/master/test/manual/persist.html

Fixed this demo for usage of  deprecated api.
http://codepen.io/egjs/pen/EjPzxR
