### ISSUE TITLE
How about support 'start' event at flicking?

### ISSUE THREAD

**Issue by sculove** [naver/egjs#268]
## Description
When flicking is auto rolling by programming, user should stop rolling.
flicking dose not support `start`(?) event.

**Comment by netil** [comment]
It's okay dispatch an 'start' event on touch, but there is ambiguity on that.
When panel is animating, user's touch is disabled, during move.

What is the proper action, or expectation on that circumstances?

**Comment by netil** [comment]
Better add bulletproof code to ignore move api call, during user hold.
I'll make PR for that.
