### ISSUE TITLE
1.2.0 script error

### ISSUE THREAD

**Issue by kimshinelove** [naver/egjs#274]
## Description
The logic which works correctly on 1.1.0, but gives error on 1.2.0.
I looked up and reproduced as below.

### reproduce
**when:**
```
$(el).stop();
```

**then**
![2016-06-30 7 42 58](https://cloud.githubusercontent.com/assets/1567151/16485619/de756a98-3efa-11e6-9c6d-a2e2545d4a0c.png)

**Comment by ajaxpf** [comment]
@kimshinelove, I translated your issue. We're trying to make all communications on english :)

**Comment by jongmoon** [comment]
@kimshinelove Thank you very much for reporting error!

It is a BUG which occurs on no-animate element.
I've just pushed request(https://github.com/naver/egjs/pull/276)

I'll send you fixed version as soon as possible.
