### ISSUE TITLE
No animation after a pen gesture when the value is on the edge area

### ISSUE THREAD

**Issue by happyhj** [naver/egjs#284]
## Description

Making a pan gesture when value is on the edge area.
It always have no animation after touch end.
## Steps to check or reproduce

![](http://i.imgur.com/30eVep4.gif)
http://codepen.io/happyhj/pen/KrvWAJ

**Comment by happyhj** [comment]
Have to discuss specs related this issue. 
It'll done until next milestone.

**Comment by sculove** [comment]
f/w https://github.com/naver/egjs-movablecoord/issues/3
