### ISSUE TITLE
How about change Test Framework?

### ISSUE THREAD

**Issue by sculove** [naver/egjs#287]
## Description

check BDD test tool

**Comment by sculove** [comment]
ref. https://github.com/naver/egjs/issues/83#issuecomment-231654717

**Comment by sculove** [comment]
## consideration 
- Is the mocking posible?
- Is the test code recyclable?
- Does we have to use es6 in test?
- Is coverage measurement possible in es6?
- etc...

**Comment by sculove** [comment]
- Is the mocking posible? 
  - `Yes`
  - babel-plugin-rewire

- Is the test code recyclable?
  - `No` if you use module.invoke, you should change test code.

- Does we have to use es6 in test?
  - mocha supports es6 `--compilers `
  - QUnit doesn't support es6 

- Is coverage measurement possible in es6?
  - `Yes`  `isparta-loader`

**Comment by mixed** [comment]
check coding convention

**Comment by sculove** [comment]
### Test framework guide
- Mocha + Chai + Sinon + babel-plugin-rewire

**Comment by sculove** [comment]
babel-plugin-rewire conflict with isparta.
therefore we chagne mocking tool to `inject loader`
