### ISSUE TITLE
MovableCoord - increase default threashold value options for Hammer

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs#291]
## Description

It's not a bug. but It is need to be discussed.

current threashold = 0,
But in recent device browsers, browser sends `touch offset` more correctly(?) . So when moved vertically or horizontally, sometimes Hammer does not recognize it as vertical  or horizontal perfectly.

For example when you touches screen vertically on HORIZONTAL mode, Hammer sometimes thinks it as horizontal movement by 1~ 2px.

**Comment by sculove** [comment]
@jongmoon Could you give us some information like browser test?

**Comment by sculove** [comment]
Issue moved to [naver/egjs-axes #39](https://github.com/naver/egjs-axes/issues/39) via [**ZenHub**](https://www.zenhub.com/)
