### ISSUE TITLE
separate eg.agent from eg

### ISSUE THREAD

**Issue by sculove** [naver/egjs#323]
## Description
eg.agent source is bigger and an agent isn't necessary for all egjs.

**Comment by sculove** [comment]
### AS-IS
eg.agent() -> UAParser.create -> resultCache[eg] -> eg.hook

### TO-BE
1. all : eg move to eg.util
- eg.blabla=> eg.utils.blabla => separate eg.utils
2. only agent
- eg.agent() => eg.Agent.create -> resultCache[eg] -> eg.hook

**Comment by netil** [comment]
Due to the division of agent as separate file, test files located on `manual and unit` folder, should be updated to include `./src/agent.js`

**Comment by sculove** [comment]
@netil I miss `manual` folder. ok. thanks
