### ISSUE TITLE
configurate and generate to egjs dependencies

### ISSUE THREAD

**Issue by kishu** [naver/egjs#338]
## Description

Let me know if there is wrong dependencies information each `egjs` modules.
If you have any idea about configurate and generate to egjs dependencies, comment it.

`egjs` should has configuration file that defined dependencies for `egjs custom downloader`.
If defined dependencies information in each `egjs` source files, like comments, configuration file is generated to use `grunt`. 

This is the example that defined dependencies for `movableCoord.js`.

```
...
* @dependencies class, cssPrefix, rotate, scrollEnd
* @libraries hammer.js
...
```

The configuration of dependencies file that generated like below

```
{
    "version": "1.2.0-snapshot",
    "components": [
        {
            "name": "movableCoord",
            "type": "component",
            "libraries": [
                "hammer.js"
            ],
            "dependencies": [
                "module",
                "eg",
                "class",
                "cssPrefix",
                "rotate",
                "scrollEnd"
            ]
        },
...
}
```

Table of egjs module's dependencies.(If there is anything wrong, please let me know.)

| name | type | dependencies | libraries |
| --- | --- | --- | --- |
| eg | core | module | N/A |
| component | core | module, eg | N/A |
| agent | component | module, eg | N/A |
| class | component | module, eg | N/A |
| filcking | component | module, eg, class, cssPrefix, movableCoord, rotate, scrollEnd | N/A |
| infiniteGrid | component | module, eg, cssPrefix, class, component, persist | N/A |
| movableCoord | component | module, eg, class, cssPrefix, rotate, scrollEnd | hammer.js |
| visible | component | module, eg, class, cssPrefix, scrollEnd | N/A |
| cssPrefix | extension | module, eg | N/A |
| pauseResume | extension | module, eg |  |
| persist | extension | module, eg | N/A |
| rotate | extension | module, eg | N/A |
| scrollEnd | extension | module, eg | N/A |
| transform | extension | module, eg | N/A |

**Comment by jongmoon** [comment]
They almost have dependency on jquery.

**Comment by kishu** [comment]
jQuery is excluded to egjs packaged file. It is dispensable.

**Comment by kishu** [comment]
test after 1.3.0 release.

**Comment by kishu** [comment]
Ready for test.

**Comment by sculove** [comment]
a cssPrefix has a dependency on jQuery version.
the dependency of flicking are `module, eg, class, component, movableCoord, ~~rotate, scrollEnd~~, cssPrefix(due to jQuery) `
the dependency of infiniteGrid are `module, eg, class, component, ~~persist~~, cssPrefix(due to jQuery) `
the dependency of visible are `module, eg, class,  ~~scrollEnd~~, cssPrefix(due to jQuery) `

**Comment by kishu** [comment]
We need to discuss how to develop egjs custom downloader again. It should proceed with egjs conversion works. There is much uncertainty about improving at this milestone(1.4.0).

**Comment by sculove** [comment]
egjs 2.0 provide each repository. There is no need to proceed.
