### ISSUE TITLE
Intent to apply CSS containment

### ISSUE THREAD

**Issue by netil** [naver/egjs#350]
## Description

For some components, can be useuful improving rendering cost with CSS containment property.
https://developers.google.com/web/updates/2016/06/css-containment

Try to find if it's applicable.

**Comment by netil** [comment]
There're many behavioural causing side effects.
When panels are fixed size is worth to apply, but there's no guarantee of external(ex. intentional trigger) layout transformation.

Try research and look for more practical use cases of that spec. keeping this issue for later.

**Comment by sculove** [comment]
Issue moved to [naver/egjs-infinitegrid #21](https://github.com/naver/egjs-infinitegrid/issues/21) via [**ZenHub**](https://www.zenhub.com/)
