### ISSUE TITLE
Intent to ship 'previewPadding' in percent value.

### ISSUE THREAD

**Issue by netil** [naver/egjs#359]
## Description

For `previewPadding` options, only `px` values are allowed.
To be responsible, it should be act on `%`(relative wrapper element) values too.
## Steps to check or reproduce

``` js
 new eg.Flicking("#mflick", {
    previewPadding: [ "10%", "20%" ],
    circular: true
});
```

**Comment by netil** [comment]
There's ambiguity on this.
If percentage values are given, what that values are based on?
- Wrapper element
- screen
- viewport (in case of desktop this will be browser's size)

**Comment by netil** [comment]
As a result on internal discussion,
- `wrapper` is the base element 
- isn't must functionality for this moment, but will be useful providing

Keep for later shipment

**Comment by netil** [comment]
Try implement on v2

**Comment by sculove** [comment]
Issue moved to [naver/egjs-flicking #19](https://github.com/naver/egjs-flicking/issues/19) via [**ZenHub**](https://www.zenhub.com/)
