### ISSUE TITLE
eg.MovableCoord  always stops at the edge that circular value is true.

### ISSUE THREAD

**Issue by happyhj** [naver/egjs#360]
## Description

I think MovableCoord position should not always stop at the edge that circular value is true.
## Steps to check or reproduce

http://codepen.io/happyhj/pen/zByPjw
- The left and the right edge is circular.
- When stay mousedown while passing the edge, they pass through the edge.
- But make position pass through the side edges while mouse button up. It always stops at the edge.

**Comment by sculove** [comment]
f/w https://github.com/naver/egjs-movablecoord/issues/3
