### ISSUE TITLE
jQuery.persist.isNeeded returns wrong value.

### ISSUE THREAD

**Issue by sculove** [naver/egjs#372]
## Description
- isNeeded has to return 'true' in IE10+, iOS8 iphone5

**Comment by sculove** [comment]
we should check all browser supports

**Comment by happyhj** [comment]
### page-cache support
* PC CHROME(54.0.2840.87) : no support
* MAC safari(10.0.1) :  support
* PC Firefox(49.0.2) : no support
* PC EDGE : no support
* PC IE11 : no support
* PC IE10 : no support
* PC IE9 : no support
* ios10 safari and webview : support
* ios9 safari and webview  : support
* ios8 safari and webview  : support
* android 4.2.2
  * chrome(52) : no support
  * webview : support
* android 4.3
  * chrome(52) : no support
  * webview : support
* android 4.4.2
  * chrome(54) : no support
  * webview : no support
* android 6.0.1
  * chrome(54) : no support
  * webview : no support
