### ISSUE TITLE
Update description for refresh method in eg.visible.

### ISSUE THREAD

**Issue by happyhj** [naver/egjs#374]
## Description

The refresh method is not need to be called externally anymore when DOM changes. 
Because it caches the live collection (NodeList from getElementsByClassName) when it calls first time.
- [ ] Update jsdoc description
- [ ] Consider deprecating refresh method

**Comment by sculove** [comment]
@happyhj IE8 doesn't support `getElementsByClassName method`
Therefore, The Visible should have `refresh` method.

**Comment by kishu** [comment]
Can not use `getElementsByClassName` in IE7, so have to find the target element each time.
@happyhj Please check and close the issue.

**Comment by happyhj** [comment]
@kishu Got it. We Still need refresh method for IE8, IE7!
