### ISSUE TITLE
Update persist API doc

### ISSUE THREAD

**Issue by netil** [naver/egjs#387]
## Description

- `$.isNeeded()` isn't showing: 
  - https://github.com/naver/egjs/blob/master/src/plugin/persist.js#L249
- Omission of `persist` custom event description
  - https://github.com/naver/egjs/blob/master/src/plugin/persist.js#L82

**Comment by happyhj** [comment]
`$.persist.isNeeded` is a nested objects methods.
Will update jsdoc after reading  this link.
http://stackoverflow.com/questions/19230971/how-do-i-jsdoc-a-nested-objects-methods
