### ISSUE TITLE
Check build tool for ES6

### ISSUE THREAD

**Issue by sculove** [naver/egjs#390]
## Description

rollup is a good choice.
1. supports “tree-shaking”
2. supports "ES6 module"
3. config files supports es6
4. so simple 

also, webpack2 is good

**Comment by sculove** [comment]
https://code.lengstorf.com/learn-rollup-js/

**Comment by netil** [comment]
I agree on some portion of build tasks could be taken by 'bundlers', but I don't think it can replace every tasks we have.

**Comment by sculove** [comment]
@netil me,too
When we seperates the repository, we consider it.

**Comment by netil** [comment]
How about remove bower support simplifying to npm?

**Comment by sculove** [comment]
we decide `webpack2`
