### ISSUE TITLE
Add EDGE support to jsdoc "support" tag

### ISSUE THREAD

**Issue by happyhj** [naver/egjs#4]

**Comment by happyhj** [comment]
and need to remove "n-ios", "n-an" property from jsdoc "support" tag

**Comment by happyhj** [comment]
should add EDGE browser on QA list

**Comment by happyhj** [comment]
"Persist" is working properly on EDGE

**Comment by happyhj** [comment]
@jongmoon, 1.2.0 release manager should handle this issue.

**Comment by jongmoon** [comment]
All unit tests are tested and There's issues on Flicking, Persist.

It need to check if it can be fixed in 1.2.0.

Thanks to @happyhj. Can you upload Screen Shot?

**Comment by happyhj** [comment]
Flicking
<img width="794" alt="screen shot 2016-04-21 at 6 12 07 pm" src="https://cloud.githubusercontent.com/assets/3903575/14703822/de9cfe54-07ec-11e6-8858-141c2d22d3dc.png">
Persist
<img width="789" alt="screen shot 2016-04-21 at 6 11 40 pm" src="https://cloud.githubusercontent.com/assets/3903575/14703825/e085856a-07ec-11e6-838d-72c4ff753c4d.png">
