### ISSUE TITLE
How about process `scrollRestoration` property in Persist?

### ISSUE THREAD

**Issue by sculove** [naver/egjs#435]
## Description
The persist create the virtual bfcache (?).
When history back, the scroll position is moved by browser like chrome.
How about control `scrollRestoration` property?
```js
if ('scrollRestoration' in history) {
  // Back off, browser, I got this...
  history.scrollRestoration = 'manual';
}
```

**Comment by netil** [comment]
- Pros: Don't intervene programmatically scroll action.
- Cons: If restoration is set to manual, it means need to implement scroll restoration programmatically.

**Comment by sculove** [comment]
I think if you are using persist, it will be the user who will want to control the scrolling

**Comment by netil** [comment]
But, in other word it's unnecessary handle scroll (for that it should check exact restoration happening natively)

**Comment by sculove** [comment]
Issue moved to [naver/egjs-persist #11](https://github.com/naver/egjs-persist/issues/11) via [**ZenHub**](https://www.zenhub.com/)
