### ISSUE TITLE
Improve .resize() to handle width and height

### ISSUE THREAD

**Issue by netil** [naver/egjs#439]
## Description

Currently `.resize()`, only treat one sided dimension value.

ex.)
- when option.horizontal == true, resize only `width`
- when option.horizontal == false, resize only `height`

Improve `.resize()` to adjust width and height

**Comment by sculove** [comment]
Issue moved to [naver/egjs-flicking #17](https://github.com/naver/egjs-flicking/issues/17) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sculove** [comment]
Issue moved to [naver/egjs-flicking #18](https://github.com/naver/egjs-flicking/issues/18) via [**ZenHub**](https://www.zenhub.com/)
