### ISSUE TITLE
Sometimes InfiniteGrid can`t load data.(무한스크롤 데이터 로드 불가 현상)

### ISSUE THREAD

**Issue by ddarkchu** [naver/egjs#456]
## Description

1. http://naver.github.io/egjs/ 해당사이트 튜토리얼 (Move to http://naver.github.io/egjs/)
2.  무한 스크롤 튜토리얼 및 데모에서 스크롤 최하위 까지 내리면 데이터가 더 이상 로드 되지 않음.
(When scroll end that can`t load data in Demo.)
## Steps to check or reproduce

1. 스크롤을 데이터 로드 직전 까지 내림 ( Push the scroll down straight just before data load.)
2. 스크롤을 마우스로 드레그 해서 제일 아래로 내림. (Move the scroll down with the mouse.)

![image](https://cloud.githubusercontent.com/assets/20293843/22917832/6f1b4ab2-f2ca-11e6-830f-270aa979d4be.png)

**Comment by mixed** [comment]
@ddarkchu 
Thank you for reporting. We are going to check this issue soon.

**Comment by sculove** [comment]
it's not a bug about eg.infiniteGrid.
this is a bug about demo. I try to consider this issue. Thanks

**Comment by sculove** [comment]
egjs-infinitegrid 2.0 change this demo to overflow:scroll type
