### ISSUE TITLE
Reusing trigger customEvent object

### ISSUE THREAD

**Issue by VReality64** [naver/egjs#458]
I'll mention 3 things.

1. Situation I been through.
2. The thing what I expected.
3. Solution.

## Situation I been through
I have one controller and two modules. everything is class inherited from `eg.Component`.

```javascript
// Controller, Module A, Module B
var instance = new eg.Class.extend(eg.Component, {
  // ...
});
```

I tried handle custom event state between modules and controller using `customEvent.stop()` function. But stop was not worked.

> [Trigger Docs](http://naver.github.io/egjs/latest/doc/component.js.html#line67): If the stop() method is called by a custom event handler, it will return false and prevent the event from occurring.

Here are code.
```javascript
// Controller has Module A. Module A has Module B.
// every callback function is wrapped `$.proxy` with `this` context.
// this.module.on('eventName', $.proxy(callback, this));

// In Controller
moduleA.on('beforeSelect', function (event) {
  event.stop();
});

// In Module A
moduleB.on('beforeSelect', function (event) {
  this.trigger('beforeSelect', event);	// reuse event object
});

// In Module B
this.on('click', function (event) {
  if (this.trigger('beforeSelect')) {
    this.select('data');
  }
})
```

## The thing what I expected
Code describes that if controller calls `event.stop()` then doesn't execute `moduleB.select()`. because `stop()` makes `trigger` return `false`.

I think reusing custom event is common case. normally custom event has data, so it was broadcasted to system.

But when it reused, `isCanceled` variable was overridden.
```javascript
trigger: function(eventName, customEvent) {
  // event(data) Object are alive.
  customEvent = customEvent || {};
  
  // ...
  // isCanceled variable is overridden.
  var isCanceled = false;
  
  // ...
  return !isCanceled;
},
```
If intended, it is **notable**.

## Solution
I changed middle module. **not re-used event object**
```javascript
// [Before] In Module A
moduleB.on('beforeSelect', function (event) {
  this.trigger('beforeSelect', event);	// reuse event object
}
           
// [Changed] In Module A
moduleB.on('beforeSelect', function (event) {
  var stop = !this.trigger("beforeSelect");	// not re-used event object
  if (stop) {
    event.stop();
  }
}
```
I made [JS fiddle example](https://jsfiddle.net/ipark/bj4rp2mL/1/). you can reproduce my situation.

## Question
I can't sure what is right, so just want to know decision history. what philosophy / thoughts leads this conclusion?

**Comment by mixed** [comment]
@VReality64 
Thank you for your report. I am going to anwser it soon. 😄

**Comment by mixed** [comment]
I think that This case is very important issue. Sometimes Component has not to fire event. So if trigger add option like boolean for event fire condition. I think differently It is duplicate feature(`stop` method). So. It need more idea.

**Comment by sculove** [comment]
Issue moved to [naver/egjs-component #19](https://github.com/naver/egjs-component/issues/19) via [**ZenHub**](https://www.zenhub.com/)
