### ISSUE TITLE
if the sum of previewPadding is greater than height

### ISSUE THREAD

**Issue by sculove** [naver/egjs#460]
## Steps to check or reproduce

`When the height of #mflick is 50px`

```js
var some = new eg.Flicking("#mflick", {
    previewPadding : [ 40, 40 ],
    horizontal: false
});
```

**Comment by netil** [comment]
In that case the total of each preview area overpass the panel's height.

I think it is caused by mal usage of applying values and there is ambiguity. 
What is the expected behavior or result for that? we should care on all cases which aren't normal approach?

**Comment by netil** [comment]
There're too many exceptions to handle if we start handle all unexpected usages.
This is clear of mal applying option value, and user can clearly notice that.
