### ISSUE TITLE
Ambiguity of getting elements

### ISSUE THREAD

**Issue by netil** [naver/egjs#467]
## Description

Getting top/bottom elements API description and return value has ambiguity.

> Returns a card element at the top of a layout.
- http://naver.github.io/egjs/latest/doc/eg.InfiniteGrid.html#getTopElement

> Returns a card element at the bottom of a layout.
- http://naver.github.io/egjs/latest/doc/eg.InfiniteGrid.html#getBottomElement

The descriptions are likely saying getting result of top or last element, but if grids are divided in several columns, which one is the expected?

For example, in the following case, `.getBottomElement()`, return the right element? or the left?

![image](https://cloud.githubusercontent.com/assets/2178435/23598464/f86f78ac-027d-11e7-9362-f52f5610cb2b.png)

**Comment by sculove** [comment]
I will add jsdoc comment.

**Comment by sculove** [comment]
The last element is used to find the index of the next data to fetch.
we should fix it.
