### ISSUE TITLE
MovableCoord::_getCicularPos() is not circular perfectly.

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs#481]
## Description

This function makes holes on boundary value.

## Steps to check or reproduce

For example,

```js
getCircularPos([6, 0], [-5, 0], [5, 0], [true, true, true, true])
```

It returns`-5`,
The how about below result?

```js
getCircularPos([-6, 0], [-5, 0], [5, 0], [true, true, true, true])
```

It returns `4`

The return rules are different each other!

**Comment by sculove** [comment]
applied 2.0.0-rc.1
