### ISSUE TITLE
call 'resize()' when preview padding was applied, panel size doesn't change

### ISSUE THREAD

**Issue by weumj** [naver/egjs#489]
## Description
Calling `flicking.resize()` when device rotate event occurs, each panel's size should change appropriately.

But when preview padding was applied, calling 'resize()' did not change each panel's size.

### portrait
![image](https://user-images.githubusercontent.com/7656085/26961398-3fac5650-4d19-11e7-80ef-8771d0e3f787.png)

### after device rotate to horizontal (current)
![image](https://user-images.githubusercontent.com/7656085/26961402-4287fc6c-4d19-11e7-9a1c-a568121cb378.png)

### after device rotate to horizontal (expected)
![image](https://user-images.githubusercontent.com/7656085/26961388-2f482262-4d19-11e7-84c4-5ba5f4a6ed65.png)

## Steps to check or reproduce

1. create a `Flicking` object and listen `device rotate` event
2. invoke `device rotate` event

I think that [`_checkPadding()`](https://github.com/naver/egjs/blob/master/src/flicking.js#L1400) caused this problem.

### Javascript
```js
const flicking = new eg.Flicking("#flick", {
	duration: 200,
	hwAccelerable: true,
	threshold: 70,
	previewPadding: [0, 16],
	circular: false,
	adaptiveHeight: true
});

$(window).on("rotate", () => flicking.resize());
```

### HTML
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0,user-scalable=yes">
</head>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/egjs/1.5.0/pkgd/eg.pkgd.min.js"></script>
  <body>
    <div id="flick">
      <div>panel 1</div>
      <div>panel 2</div>
      <div>panel 3</div>
      <div>panel 4</div>
      <div>panel 5</div>
    </div>
  </body>
</html>
```

### CSS
```css
body {
   margin: 0;
   padding:0;
}
#flick {
   height: 200px;
}
#flick div {
   border: 1px solid rgba(0,0,0,0.08);
   background-color: #bbbbbb;
   height: 100%;
   font-size: 15px;
}
```

**Comment by netil** [comment]
Confirmed the bug, I'll check for the fix.
- https://output.jsbin.com/feqewux
