### ISSUE TITLE
What is the character of the egjs logo?

### ISSUE THREAD

**Issue by tnraro** [naver/egjs#511]
Hello,

I'm not sure if this is the appropriate place to ask, but I'm curious about the character featured in the EGJS logo.

I was wondering if you could tell me what meaning this character holds and what its design motif is based on.

Thank you for your time and response.

**Comment by malangfox** [comment]
Hello @tnraro.

EGJS's logo is designed from a monkey, an animal with a variety of skills.
We are always happy to answer any questions you may have!

**Comment by tnraro** [comment]
Thanks for the answer!
