### ISSUE TITLE
Check egjs.github.io

### ISSUE THREAD

**Issue by mixed** [naver/egjs#61]
https://help.github.com/articles/creating-project-pages-manually/

**Comment by kishu** [comment]
https://naver.github.io/egjs

**Comment by mixed** [comment]
@kishu 
AWESOME!!

**Comment by kishu** [comment]
I'm gonna change "egjs github pages" to "https://naver.github.io/egjs"!
 - remove https://github.com/egjs/egjs.github.io
 - change all links of "https://egjs.github.io" to "https://naver.github.io/egjs"
 - all egjs "dist" references. (in codepen.io, etc)

Let me know any side effect of change!

**Comment by sculove** [comment]
we sholud change readme.md and package.json
