### ISSUE TITLE
Check coverage tracking system.

### ISSUE THREAD

**Issue by mixed** [naver/egjs#63]
https://coveralls.io/

We can check test coverage. So Decreasing test coverage we can recevie massage.

**Comment by netil** [comment]
https://codeclimate.com will be good candidate also.

IMO it brings more functionality than coveralls and has good integration with TravisCI.
https://docs.travis-ci.com/user/code-climate/

**Comment by netil** [comment]
- Test coverage url : https://codeclimate.com/github/naver/egjs/coverage

Test coverage will not show all of the files. According codeclimate doc will show only for the matching commit.
http://docs.classic.codeclimate.com/article/220-help-im-having-trouble-with-test-coverage#no_coverage
We'll only display test coverage data if we've also analyzed the matching commit. If you're not sure, check the SHA on your Feed page.
