### ISSUE TITLE
Remove testee task

### ISSUE THREAD

**Issue by sculove** [naver/egjs#84]
if we use karma, testee is unnecessary

- package script, dependecy
- grunt task

@kishu plz, check this issue

**Comment by kishu** [comment]
After finish BrowserStack test environment, we doesn't need "testee" any more.
I'll remove it soon. Thank you for letting me know.

**Comment by kishu** [comment]
This issue has already been done by @happyhj.
Ref: 5a8c90b

Thanks guy!
